name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Only create release for tags
          tagName: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
          releaseName: ${{ startsWith(github.ref, 'refs/tags/') && format('Temperature Chart App v{0}', github.ref_name) || '' }}
          releaseBody: ${{ startsWith(github.ref, 'refs/tags/') && 'Temperature Chart Desktop Application

            ## Features
            - Import and visualize CSV temperature data
            - Interactive charts with ECharts integration
            - Export charts as PNG images
            - Save/load analysis sessions (.tdproj files)
            - Dark/light theme support
            - Jump to specific time functionality
            - Multi-channel temperature monitoring (up to 12 channels)
            
            ## Installation
            - **Windows**: Download the `.msi` installer
            - **macOS**: Download the `.dmg` file  
            - **Linux**: Download the `.AppImage` file
            
            Built with Tauri + React + TypeScript + ECharts' || '' }}
          releaseDraft: ${{ startsWith(github.ref, 'refs/tags/') }}
          prerelease: false
          includeUpdaterJson: false

